### ISSUE TITLE
InsecureSkipVerify in HTTP Client for Federation

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/chainsource-gateway#104]
**Description of the issue:**

I am not sure if it makes sense for the node sending the federation request to not also have to verify the identity of the node it is contacting. Definitely can be up for further discussion

![image](https://github.com/DBOMproject/chainsource-gateway/assets/57193503/dde55ecf-414f-40da-87e9-68600689e202)

Also in GetRequest

**Submitting a pull request?**

Are you willing to submit a pull request to solve this issue? (Yes/No):

**Comment by irajeshegde** [comment]
@mathisonryan - You are right. In the current `2.0.0-alpha-1` version, lightweight mTLS is implemented between nodes with a single certificate. Since this feature was still under development `InsecureSkipVerify` was set to `true`. 

Fixed it - [here](https://github.com/DBOMproject/chainsource-gateway/commit/5f48d22260ab53b1565bf07c9ee77353432aafad)
